"""
report.py — writes evidence/attack-correlation_<timestamp>.md, matching the
style of hunt.sh / generate-report.sh's output: a self-hashing markdown
file that's readable on its own and slots into `make seal`'s manifest.
"""
from __future__ import annotations
import hashlib
import time
from .pipeline import RunSummary
from .config import PROMPT_VERSION


def write_report(summary: RunSummary, cfg, evidence_dir: str, dry_run: bool) -> str:
    ts = time.strftime("%Y%m%d_%H%M%S")
    out_path = f"{evidence_dir}/attack-correlation_{ts}.md"

    lines: list[str] = []
    lines.append("# 🔗 AI-Assisted Attack Chain Correlation Report\n")
    lines.append("**Generated by** `scripts/correlate.py`  ")
    lines.append(f"**Report time:** {time.strftime('%Y-%m-%d %H:%M:%S')}  ")
    lines.append(f"**Mode:** {'DRY RUN (no API calls made)' if dry_run else cfg.mode}  ")
    lines.append(f"**Model:** {cfg.model if cfg.mode == 'gemini' else 'mock (no real model)'}  ")
    lines.append(f"**Prompt version:** {PROMPT_VERSION}\n")
    lines.append("---\n")

    lines.append("## Run Summary\n")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Total alerts considered | {summary.total_alerts} |")
    lines.append(f"| Candidate incidents (2+ correlated events) | {summary.candidate_incidents} |")
    lines.append(f"| Isolated alerts skipped (no Gemini call needed) | {summary.skipped_isolated} |")
    lines.append(f"| Cache hits | {summary.cached} |")
    lines.append(f"| New API calls made | {summary.new_api_calls} |")
    lines.append(f"| Request limit reached mid-run | {'yes' if summary.limit_reached else 'no'} |")
    lines.append("")
    lines.append("---\n")

    lines.append("## Incidents\n")
    if not summary.incidents:
        lines.append("_No multi-event candidate incidents found in this window — "
                      "either no alerts fired, or every alert was isolated._\n")
    for inc in summary.incidents:
        lines.append(f"### {inc.incident_id} — status: `{inc.ai_status}`\n")
        lines.append(f"- **Candidate event IDs:** `{', '.join(inc.candidate_event_ids)}`")
        if inc.model:
            lines.append(f"- **Model:** {inc.model}")
        if inc.detail:
            lines.append(f"- **Detail:** {inc.detail}")
        if inc.processing_ms:
            lines.append(f"- **Processing time:** {inc.processing_ms} ms")

        r = inc.result
        if r:
            lines.append(f"- **Correlated:** {r.get('is_correlated')} "
                          f"(confidence: {r.get('confidence')})")
            if r.get("attack_chain"):
                lines.append("\n**Attack chain:**\n")
                lines.append("| Stage | Event IDs | Confidence |")
                lines.append("|---|---|---|")
                for stage in r["attack_chain"]:
                    lines.append(f"| {stage['stage']} | {', '.join(stage['event_ids'])} | {stage['confidence']} |")
            if r.get("relationships"):
                lines.append("\n**Relationships:**\n")
                lines.append("| From | To | Relationship | Confidence | Reason |")
                lines.append("|---|---|---|---|---|")
                for rel in r["relationships"]:
                    lines.append(f"| {rel['from_event']} | {rel['to_event']} | {rel['relationship']} "
                                  f"| {rel['confidence']} | {rel['reason']} |")
            if r.get("mitre_attack"):
                lines.append("\n**MITRE ATT&CK techniques:**\n")
                lines.append("| Technique | Event IDs | Confidence |")
                lines.append("|---|---|---|")
                for m in r["mitre_attack"]:
                    lines.append(f"| {m['technique']} | {', '.join(m['event_ids'])} | {m['confidence']} |")
            if r.get("uncertainties"):
                lines.append("\n**Uncertainties (explicitly flagged, not inferred):**\n")
                for u in r["uncertainties"]:
                    lines.append(f"- {u}")
        lines.append("\n---\n")

    lines.append("## Method\n")
    lines.append("- Detection remains entirely the job of Wazuh and Suricata; this report only")
    lines.append("  *correlates already-generated alerts* — no new detection logic was added.")
    lines.append("- Candidate grouping is deterministic (shared source IP + a second signal, within")
    lines.append(f"  a {cfg.correlation_window_seconds}s window) and runs before any AI call.")
    lines.append("- Isolated alerts and cached candidate groups never reach the Gemini API.")
    lines.append("- Raw alerts are never discarded or overwritten by AI output — see alerts.json")
    lines.append("  on wazuh-server for the original evidence.")
    lines.append("")

    content = "\n".join(lines)
    self_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
    content += "\n---\n\n## Evidence Integrity\n\n```\n"
    content += f"SHA-256: {self_hash}  {out_path.split('/')[-1]}\n"
    content += f"Sealed:  {time.strftime('%Y-%m-%d %H:%M:%S %z')}\n```\n\n"
    content += "> Run `make seal` to include this file in the tamper-evident evidence manifest.\n"

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    return out_path
